export const CURRENT_SCREEN = 'CURRENT_SCREEN'
export const LOADER_SHOW = 'LOADER_SHOW'
export const LOADER_HIDE = 'LOADER_HIDE'

export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REGISTER = 'AUTH_REGISTER'
export const AUTH_RECOVERY = 'AUTH_RECOVERY'

export const GAME_CREATE = 'GAME_CREATE'
export const GAME_SAVE = 'GAME_SAVE'

export const ALERTS_VALIDATE = 'ALERTS_VALIDATE'
export const ALERTS_VALIDATE_CLEAR = 'ALERTS_VALIDATE_CLEAR'
export const ALERTS_ERRORS = 'ALERTS_ERRORS'
export const ALERTS_ERRORS_CLEAR = 'ALERTS_ERRORS_CLEAR'
export const ALERTS_MESSAGE = 'ALERTS_MESSAGE'
export const ALERTS_MESSAGE_CLEAR = 'ALERTS_MESSAGE_CLEAR'